sudo: required
dist: trusty
matrix:
   include:
      - jdk: openjdk8
        os: linux
      - jdk: oraclejdk7
        os: linux
      - jdk: oraclejdk8
        os: linux
      - os: osx
before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
script:
   - mvn test
cache:
   directories:
      - $HOME/.m2
