sudo: required
dist: trusty
matrix:
   include:
      - jdk: openjdk8
        os: linux
      - jdk: oraclejdk7
        os: linux
      - jdk: oraclejdk8
        os: linux
      - os: osx
script:
   - mvn test
